### ISSUE TITLE
Github Action does not Label PRs

### ISSUE THREAD

**Issue by ChrisOwen101** [JulienKode/team-labeler-action#88] opened 2021-05-26 21:51 UTC
Hi, just wondering if this project is still supported as I'm struggling to get it to work

- Github Action: https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/master/.github/workflows/team-labeler.yml
- Teams Config: https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/blob/master/.github/teams.yml
- Example Run: https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/runs/2679581247?check_suite_focus=true

As you can see, I'd expect my PR to be tagged with the `Improvement` label.

Do you have any advice?

**Comment by ChrisOwen101** [comment] 2021-05-26 21:51
@JulienKode

**Comment by JulienKode** [comment] 2021-06-02 19:53
Thanks for submitting this issue,

Sorry that you have some issue with it 

Can you try the following version please ?

```
name: "team-labeller"
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: JulienKode/team-labeler-action@v0.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

**Comment by JulienKode** [comment] 2021-06-02 19:54
I'll check on my side to reproduce this issue @ChrisOwen101

**Comment by ChrisOwen101** [comment] 2021-06-03 09:58
Thanks @JulienKode 

You can find a run of the Github Action here with the code you've supplied above.

https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/actions/runs/902392771

I can confirm that it is currently not working. 

Happy to do whatever else you need to help fix this 😊

**Comment by JulienKode** [comment] 2021-06-05 13:13
Thanks for your feedback @ChrisOwen101 

I've try to create pull request on your repo, but it seems GitHub actions does not run when I do a pull request 

I've try to create a new repo with the minimal setup needed for the team labeller action
https://github.com/JulienKode/team-labeler-action-test

I'll continue to investigate on this issue

**Comment by ChrisOwen101** [comment] 2021-06-09 14:41
@JulienKode - You can manually run the code by going here

https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/actions/workflows/team-labeler.yml

And clicking on "Run Workflow"

![image](https://user-images.githubusercontent.com/5181870/121376003-122a1a00-c939-11eb-93b8-de8c9944280d.png)

**Comment by JulienKode** [comment] 2021-06-10 06:17
Seems github does not suggest it to me 

![Screenshot 2021-06-10 at 08 17 20](https://user-images.githubusercontent.com/7658664/121474381-4b5b9c00-c9c4-11eb-808f-61ae7d260584.png)

**Comment by ChrisOwen101** [comment] 2021-06-10 07:46
@JulienKode I've invited you to have Maintain access for the repo - you should be able to run it now :)

**Comment by JulienKode** [comment] 2021-06-10 08:09
Thanks @ChrisOwen101

**Comment by JulienKode** [comment] 2021-06-11 20:25
I'm having this issue right now: 

<img width="1239" alt="Screenshot 2021-06-11 at 22 24 54" src="https://user-images.githubusercontent.com/7658664/121744883-db542f80-cb03-11eb-8291-eaeb7c4413a3.png">

Looks close to https://github.com/actions/labeler/issues/12

**Comment by JulienKode** [comment] 2021-06-11 20:30
@ChrisOwen101 

when you go to: 
https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week1/settings/actions

Did you have the following config ? 
<img width="1340" alt="Screenshot 2021-06-11 at 22 30 33" src="https://user-images.githubusercontent.com/7658664/121745485-a5637b00-cb04-11eb-9528-5c39a888c52a.png">

**Comment by ChrisOwen101** [comment] 2021-06-14 15:00
@JulienKode 

Yep, we've got that Setting on by default.

**Comment by JulienKode** [comment] 2021-07-14 07:28
I've continue to take a look at this issue:

I've clone the repo on my side and push the repo to a repository that I own: https://github.com/JulienKode/JavaScript-Core-1-Coursework-Week1-test/pull/1 

Then I've just create this pull request 

The action run well and I have the label with the exact same code and repository that you have setup

So you did everything good, I've think the issue is related to the config or right for the actions on the repository 

If you want we can setup a call to take a look at the config ?

**Comment by dunklesToast** [comment] 2021-08-04 14:30
I had the same problem. Turns out, you need to create the labels manually before.
You can do that here: https://github.com/<user/org>/<repo>/issues/labels

**Comment by JulienKode** [comment] 2021-08-04 18:40
Thanks for catching this @dunklesToast, it help a lot 

I didn't had to create it for my personal GitHub, so I guess this is related to GitHub org ?

**Comment by dunklesToast** [comment] 2021-08-04 20:22
Hmm good question. I did use it on an organisation. Let me try in a personal project. Also, Markdown messed up the URL, I fixed it.

**Comment by dunklesToast** [comment] 2021-08-04 20:58
Okay weird. I tested it via the "raw" GitHub API. It worked in Organization and on private projects without creating the label first. I wonder why I had to create them while using this action.

**Comment by JulienKode** [comment] 2022-02-10 20:27
@dunklesToast @ChrisOwen101 does this issue is solved now ? or you still experience it

**Comment by dunklesToast** [comment] 2022-04-24 14:14
Seems to be resolved for me

**Comment by JulienKode** [comment] 2022-04-25 07:46
Thanks for your feedback @dunklesToast 

I close this issue 

Feel free to re-open it if needed

**Closed by JulienKode** 2022-04-25 07:46 UTC
